ALTER TABLE card_payments ADD COLUMN IF NOT EXISTS entry_mode VARCHAR(30);
ALTER TABLE card_payments ADD COLUMN IF NOT EXISTS acq_mid VARCHAR(50);
ALTER TABLE card_payments ADD COLUMN IF NOT EXISTS acq_tid VARCHAR(50);
ALTER TABLE card_payments ADD COLUMN IF NOT EXISTS pos_message_id VARCHAR(100);
