<script setup lang="ts">
import { computed, ref } from 'vue'
import { RouterLink } from 'vue-router'
import { useQuery } from '@tanstack/vue-query'
import { z } from 'zod'
import { apiBaseUrls, getErrorMessage, posApi, requestData } from '../lib/api'
import { revenueSchema, summarySchema } from '../lib/schemas'

const days = ref(90)
const storeType = ref('')
const startDate = ref('')
const endDate = ref('')
const sortBy = ref<'revenue' | 'totalSold' | 'productName'>('revenue')
const dateRange = computed(() => { if (startDate.value && endDate.value) return { startDate: startDate.value, endDate: endDate.value }; const end = new Date(); const start = new Date(end); start.setDate(start.getDate() - days.value + 1); return { startDate: start.toISOString().slice(0, 10), endDate: end.toISOString().slice(0, 10) } })
const queryFilters = computed(() => ({ ...dateRange.value, ...(storeType.value ? { storeType: storeType.value } : {}) }))
const summary = useQuery({ queryKey: computed(() => ['dashboard', 'summary', queryFilters.value]), queryFn: () => requestData(posApi, { method: 'GET', url: '/dashboard/summary', params: queryFilters.value }, summarySchema) })
const revenue = useQuery({ queryKey: computed(() => ['dashboard', 'revenue', queryFilters.value]), queryFn: () => requestData(posApi, { method: 'GET', url: '/dashboard/revenue', params: { ...queryFilters.value, days: days.value } }, z.array(revenueSchema)) })
const topProducts = useQuery({ queryKey: computed(() => ['dashboard', 'top-products', storeType.value]), queryFn: () => requestData(posApi, { method: 'GET', url: '/dashboard/top-products', params: { limit: 10, ...(storeType.value ? { storeType: storeType.value } : {}) } }, z.array(z.object({ productId: z.number(), productName: z.string(), totalSold: z.number(), revenue: z.number() }))) })
const summaryPending = computed(() => summary.isPending.value)
const summaryError = computed(() => summary.isError.value)
const revenueFetching = computed(() => revenue.isFetching.value)
const revenuePending = computed(() => revenue.isPending.value)
const topProductsPending = computed(() => topProducts.isPending.value)
const summaryErrorMessage = computed(() => getErrorMessage(summary.error.value))
const cards = computed(() => { const data = summary.data.value; if (!data) return []; return [{ label: 'Total orders', value: data.totalOrders.toLocaleString(), note: 'Across all stores', tone: 'teal', icon: '↗' }, { label: 'Gross revenue', value: `Rp ${data.totalRevenue.toLocaleString('id-ID')}`, note: 'Current period', tone: 'indigo', icon: '◈' }, { label: 'Average order', value: `Rp ${data.avgOrderValue.toLocaleString('id-ID')}`, note: 'Per completed order', tone: 'amber', icon: '◌' }, { label: 'Voided orders', value: data.voidedCount.toLocaleString(), note: 'Needs attention', tone: 'rose', icon: '!' }] })
const maxRevenue = computed(() => Math.max(1, ...(revenue.data.value?.map((point) => point.revenue) ?? [1])))
const paymentMix = computed(() => { const data = summary.data.value; if (!data) return []; const total = Math.max(1, data.cashTotal + data.cardTotal + data.qrisTotal); return [{ label: 'Cash', amount: data.cashTotal, percent: Math.round(data.cashTotal / total * 100), color: 'bg-brand-500' }, { label: 'Card', amount: data.cardTotal, percent: Math.round(data.cardTotal / total * 100), color: 'bg-indigo-500' }, { label: 'QRIS', amount: data.qrisTotal, percent: Math.round(data.qrisTotal / total * 100), color: 'bg-amber-400' }] })
const sortedTopProducts = computed(() => [...(topProducts.data.value ?? [])].sort((a, b) => sortBy.value === 'productName' ? a.productName.localeCompare(b.productName) : b[sortBy.value] - a[sortBy.value]))
function retryDashboard() { void summary.refetch(); void revenue.refetch(); void topProducts.refetch() }
function resetFilters() { storeType.value = ''; days.value = 90; startDate.value = ''; endDate.value = ''; sortBy.value = 'revenue' }
</script>

<template>
  <div class="space-y-7">
    <section class="dashboard-hero"><div><p class="text-sm font-medium text-teal-100">Operational snapshot</p><h2 class="mt-2 max-w-xl text-3xl font-bold tracking-tight text-white sm:text-4xl">Everything important, at a glance.</h2><p class="mt-3 max-w-lg text-sm leading-6 text-teal-100/75">Monitor your POS performance and act on the numbers that need attention today.</p></div><div class="flex items-center gap-2 rounded-xl border border-white/15 bg-white/10 p-1"><span class="pl-3 text-xs font-medium text-teal-100/70">Period</span><select v-model="days" class="rounded-lg bg-white px-3 py-2 text-sm font-semibold text-slate-800 outline-none"><option :value="7">7 days</option><option :value="30">30 days</option><option :value="90">90 days</option></select></div></section>
    <section class="dashboard-filters"><div class="filter-heading"><span class="filter-mark">⌕</span><div><p class="filter-title">Dashboard filters</p><p class="filter-subtitle">Refine the metrics without leaving this page.</p></div></div><div class="filter-fields"><label class="filter-field"><span>Store type</span><select v-model="storeType"><option value="">All stores</option><option value="RETAIL">Retail</option><option value="FB">Food & beverage</option><option value="OUTFIT">Outfit</option><option value="ALL">All</option></select></label><label class="filter-field"><span>From</span><input v-model="startDate" type="date" /></label><label class="filter-field"><span>To</span><input v-model="endDate" type="date" /></label><button class="filter-reset" type="button" @click="resetFilters">Reset</button></div></section>
    <div v-if="summaryError" class="status-error"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p class="font-semibold">Unable to load dashboard data</p><p class="mt-1 text-xs text-rose-600">{{ summaryErrorMessage }}</p><p class="mt-2 break-all text-[10px] text-rose-400">Endpoint: {{ apiBaseUrls.pos }}/dashboard/summary</p></div><button class="rounded-lg border border-rose-200 bg-white px-3 py-2 text-xs font-bold text-rose-700 hover:bg-rose-50" @click="retryDashboard">Retry</button></div></div>
    <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article v-for="card in cards" :key="card.label" class="stat-card"><div class="flex items-start justify-between"><div><p class="text-sm font-medium text-slate-500">{{ card.label }}</p><p class="mt-3 text-2xl font-bold tracking-tight text-slate-900">{{ card.value }}</p></div><span :class="['grid h-10 w-10 place-items-center rounded-xl text-lg font-bold', `stat-${card.tone}`]">{{ card.icon }}</span></div><p class="mt-5 text-xs font-medium text-slate-400">{{ card.note }}</p></article><template v-if="summaryPending"><div v-for="n in 4" :key="n" class="h-40 animate-pulse rounded-2xl bg-slate-200/80" /></template></section>
    <section class="dashboard-panels grid gap-5 lg:grid-cols-[minmax(0,1.5fr)_minmax(300px,1fr)]">
      <article class="surface-card"><div class="flex items-start justify-between"><div><h3 class="section-title">Revenue trend</h3><p class="section-subtitle">Daily performance from POS orders</p></div><span v-if="revenueFetching" class="live-indicator"><i /> Updating</span></div><div class="dashboard-chart mt-8 flex h-56 items-end gap-2 sm:gap-4"><div v-for="point in revenue.data.value" :key="point.date" class="group flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><div class="relative flex h-48 w-full items-end"><div class="revenue-bar" :style="{ height: `${Math.max(7, point.revenue / maxRevenue * 100)}%` }"><span class="revenue-tooltip">Rp {{ point.revenue.toLocaleString('id-ID') }}</span></div></div><span class="text-[10px] font-medium text-slate-400">{{ point.date.slice(5) }}</span></div><p v-if="!revenuePending && !revenue.data.value?.length" class="w-full self-center text-center text-sm text-slate-400">Belum ada data revenue untuk periode ini.</p></div></article>
      <article class="surface-card payment-panel"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><h3 class="section-title">Payment mix</h3><p class="section-subtitle">Revenue by payment method</p></div><span class="shrink-0 rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-emerald-600">Live</span></div><div class="payment-mix-list mt-8 space-y-5"><div v-for="item in paymentMix" :key="item.label" class="min-w-0"><div class="mb-2 flex items-center justify-between gap-3 text-sm"><span class="truncate font-medium text-slate-700">{{ item.label }}</span><span class="shrink-0 font-semibold text-slate-900">{{ item.percent }}%</span></div><div class="h-2 overflow-hidden rounded-full bg-slate-100"><div :class="['h-full rounded-full transition-all', item.color]" :style="{ width: `${item.percent}%` }" /></div><p class="mt-1.5 truncate text-xs text-slate-400">Rp {{ item.amount.toLocaleString('id-ID') }}</p></div><p v-if="!paymentMix.length" class="text-sm text-slate-400">Waiting for summary data...</p></div></article>
    </section>
    <section class="grid gap-5 xl:grid-cols-[1.2fr_1fr]"><article class="surface-card"><div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><h3 class="section-title">Top products</h3><p class="section-subtitle">Best performers in the selected scope</p></div><div class="flex items-center gap-3"><select v-model="sortBy" class="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-semibold text-slate-600"><option value="revenue">Sort: Revenue</option><option value="totalSold">Sort: Units sold</option><option value="productName">Sort: Name</option></select><RouterLink to="/products" class="hidden text-xs font-bold text-brand-600 hover:text-brand-700 sm:block">View products →</RouterLink></div></div><div class="mt-5 divide-y divide-slate-100"><div v-for="(product, index) in sortedTopProducts" :key="product.productId" class="flex items-center gap-3 py-3 sm:gap-4"><span class="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-slate-100 text-xs font-bold text-slate-500">{{ String(index + 1).padStart(2, '0') }}</span><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold text-slate-800">{{ product.productName }}</p><p class="mt-1 text-xs text-slate-400">{{ product.totalSold.toLocaleString() }} units sold</p></div><span class="shrink-0 text-right text-xs font-bold text-slate-800 sm:text-sm">Rp {{ product.revenue.toLocaleString('id-ID') }}</span></div><p v-if="!topProductsPending && !sortedTopProducts.length" class="py-8 text-center text-sm text-slate-400">No product data yet.</p></div></article><article class="surface-card"><h3 class="section-title">Quick actions</h3><p class="section-subtitle">Jump into common tasks</p><div class="mt-5 grid grid-cols-2 gap-3"><RouterLink to="/products" class="quick-action"><span>＋</span><b>Add product</b><small>Catalog</small></RouterLink><RouterLink to="/ads" class="quick-action"><span>▷</span><b>Upload ad</b><small>Campaigns</small></RouterLink><RouterLink to="/orders" class="quick-action"><span>↗</span><b>Review orders</b><small>Operations</small></RouterLink><RouterLink to="/users" class="quick-action"><span>♟</span><b>Manage users</b><small>Access</small></RouterLink></div></article></section>
  </div>
</template>

<style scoped>
.dashboard-hero { display: flex; justify-content: space-between; gap: 2rem; overflow: hidden; position: relative; border-radius: 1.5rem; padding: 2rem; background: radial-gradient(circle at 78% 12%, rgba(64, 196, 183, .25), transparent 28%), linear-gradient(120deg, #123b3b, #0d2528); }
.dashboard-hero::after { content: ''; position: absolute; right: -5rem; bottom: -7rem; width: 18rem; height: 18rem; border: 1px solid rgba(141, 230, 216, .2); border-radius: 999px; box-shadow: 0 0 0 2rem rgba(141,230,216,.03), 0 0 0 4rem rgba(141,230,216,.025); }
.dashboard-filters { display: flex; align-items: center; justify-content: space-between; gap: 1rem; border: 1px solid #dbe7e7; border-radius: 1rem; background: rgba(255,255,255,.8); padding: .85rem 1rem; box-shadow: 0 5px 18px rgba(15,45,49,.025); }
.filter-heading { display: flex; align-items: center; gap: .7rem; min-width: max-content; }.filter-mark { display: grid; width: 2rem; height: 2rem; place-items: center; border-radius: .65rem; background: #e5f7f4; color: #08766f; font-size: 1.15rem; }.filter-title { color: #334155; font-size: .78rem; font-weight: 750; }.filter-subtitle { margin-top: .15rem; color: #94a3b8; font-size: .68rem; }.filter-fields { display: flex; align-items: end; justify-content: flex-end; gap: .6rem; flex-wrap: wrap; }.filter-field { display: flex; flex-direction: column; gap: .3rem; color: #94a3b8; font-size: .62rem; font-weight: 700; text-transform: uppercase; letter-spacing: .05em; }.filter-field input, .filter-field select { min-width: 8.5rem; border: 1px solid #e2e8f0; border-radius: .55rem; background: white; padding: .5rem .65rem; color: #475569; font-size: .75rem; font-weight: 600; outline: none; text-transform: none; letter-spacing: normal; }.filter-field input:focus, .filter-field select:focus { border-color: #8ad8cf; box-shadow: 0 0 0 3px #e5f7f4; }.filter-reset { border: 0; border-radius: .55rem; padding: .5rem .65rem; color: #08766f; font-size: .72rem; font-weight: 700; }.filter-reset:hover { background: #e5f7f4; }
.surface-card, .stat-card { border: 1px solid #e2e8f0; border-radius: 1.25rem; background: white; padding: 1.35rem; box-shadow: 0 8px 24px rgba(15, 45, 49, .035); }
.stat-card { min-height: 10rem; transition: transform .2s, box-shadow .2s; }
.stat-card:hover { transform: translateY(-2px); box-shadow: 0 14px 30px rgba(15,45,49,.08); }
.stat-teal { background: #e5f7f4; color: #08766f; }.stat-indigo { background: #eef0ff; color: #5754c7; }.stat-amber { background: #fff6dd; color: #b77908; }.stat-rose { background: #fff0f1; color: #d34b5f; }
.section-title { font-size: 1rem; font-weight: 750; color: #172033; }.section-subtitle { margin-top: .3rem; font-size: .78rem; color: #94a3b8; }
.live-indicator { display: flex; align-items: center; gap: .4rem; color: #0f8f87; font-size: .7rem; font-weight: 700; }.live-indicator i { width: .4rem; height: .4rem; border-radius: 999px; background: #0f8f87; box-shadow: 0 0 0 4px #d7efec; }
.revenue-bar { position: relative; width: 100%; min-height: .35rem; border-radius: .5rem .5rem .25rem .25rem; background: linear-gradient(180deg, #28b5a5, #08766f); transition: height .35s ease, filter .2s; }.group:hover .revenue-bar { filter: brightness(1.08); }.revenue-tooltip { position: absolute; bottom: calc(100% + .5rem); left: 50%; display: none; transform: translateX(-50%); white-space: nowrap; border-radius: .45rem; background: #102a2b; padding: .35rem .5rem; color: white; font-size: .65rem; }.group:hover .revenue-tooltip { display: block; }
.dashboard-panels { min-width: 0; }
.dashboard-chart { min-width: 0; width: 100%; overflow-x: auto; overscroll-behavior-x: contain; }
.dashboard-chart > .group { min-width: 2.65rem; flex: 1 0 2.65rem; }
.payment-panel { min-width: 0; overflow: hidden; }
.payment-mix-list { min-width: 0; }
.quick-action { display: flex; min-height: 6.5rem; flex-direction: column; justify-content: center; border: 1px solid #e2e8f0; border-radius: .9rem; padding: .85rem; transition: border-color .2s, background .2s; }.quick-action:hover { border-color: #a6ded8; background: #f2fbfa; }.quick-action span { color: #0f8f87; font-size: 1.25rem; }.quick-action b { margin-top: .45rem; font-size: .78rem; color: #334155; }.quick-action small { margin-top: .15rem; color: #94a3b8; font-size: .65rem; }
@media (max-width: 640px) { .dashboard-hero { flex-direction: column; padding: 1.35rem; }.dashboard-hero::after { display: none; } }
@media (max-width: 1023px) { .dashboard-panels { grid-template-columns: minmax(0, 1fr); } }
@media (max-width: 800px) { .dashboard-filters { align-items: stretch; flex-direction: column; }.filter-heading { min-width: 0; }.filter-fields { justify-content: stretch; }.filter-field { flex: 1 1 8rem; }.filter-field input, .filter-field select { width: 100%; }.filter-reset { align-self: end; } }
@media (max-width: 640px) { .surface-card { padding: 1rem; }.dashboard-chart { padding-bottom: .4rem; scrollbar-width: thin; }.dashboard-chart > .group { flex: 0 0 2.65rem; }.dashboard-chart > p { min-width: 100%; }.revenue-tooltip { display: none !important; }.quick-action { min-height: 5.8rem; padding: .7rem; } }
</style>
